site_name: Python Class
site_author: Bhavya Sree Bindela
site_description: >-
  Python tutorial
theme:
  name: material
  custom_dir: material
  features:
    - tabs
plugins:
 - mknotebooks:
    execute: false
markdown_extensions:
  - pymdownx.arithmatex
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.betterem
  - pymdownx.superfences
  - markdown.extensions.footnotes
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.tables
  - markdown.extensions.abbr
  - markdown.extensions.md_in_html
  - toc:
      toc_depth : "1-1"
extra_javascript:
  - javascripts/extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BhavyaSree
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/bhavyabindela
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bhavyabindela
repo_name: BhavyaSree/PythonClass
repo_url: https://github.com/BhavyaSree/PythonClass
edit_uri: ""
# Page tree
nav:
  - Home: README.md
  - Getting started: 1.introduction.md
  - Strings & Lists: 2.strings-lists.md
  - Dictonaries, Sets & Tuples: 3.dictonaries-sets-tuples.md 
  - Operators: 4.operators.md
  - Conditional Statements: 5.conditional-statements.md
  - Methods and Functions: 7.methods-and-functions.md
  - Function Arguments: 9.function-arguments.md
  - Map Filter and Lambda Functions: 10.map-filter-lambda.md
  - Scope of Variables: 11.variables-scope.md
  - Object Oriented - Classes & Objects: 13.object-oriented.md
  - Inheritance: 14.inheritance.md
  - Polymorphism: 15.polymorphism.md
  - Special Methods in Classes: 16.special-methods-in-classes.md
  - Modules: 17.modules.md
  - Dates: 18.dates.md
  - Math: 19.math-module.md
  - Regular Expressions: 20.regular-expressions.md
  - Error Handling: 21.error-handling.md
  - Files: 22.file-handling.md
  - Decorators: 23.decorators.md
  - Generators: 24.generators.md
  - Web Scraping: 26.web-scraping.md
  - Emails: 27.emails.md
  - NumPy-1: 28.numpy-1.md
  - NumPy-2: 29.numpy-2.md
  - NumPy-3: 30.numpy-3.md
  - Pandas: 31.pandas.md
  - Pandas - Series: 32.pandas-series.md
  - Pandas - DataFrame: 33.pandas-dataframe.md
  - Practice:
    - Notebooks:
      - Day 1: Notebooks/Day1.ipynb 
      - Day 2: Notebooks/Day2.ipynb 
      - Day 3: Notebooks/Day3.ipynb
      - TicTacToe : Notebooks/TicTacToe.ipynb
      - Object Oriented : Notebooks/Classes,attributes&methods.ipynb
      - Assesment Solutions: Notebooks/FinalAssesment.ipynb
      - Binary Search: Notebooks/01.binary-search.ipynb
      - Sequential Search: Notebooks/02.sequential-search.ipynb
      - Bubble Sort: Notebooks/03.bubble-sort.ipynb
      - Selection Sort: Notebooks/04.selection-sort.ipynb
      - Fibonacci Sequence: Notebooks/05.fibonacci-sequence.ipynb
      - Prime Factors: Notebooks/06.prime-factors.ipynb
      - Binary and Decimal Conversions: Notebooks/07.binary,decimal.ipynb
      - Turtle: Notebooks/08.turtle.ipynb
      - Generating Password: Notebooks/09.password-generator.ipynb
      - Count Vowels: Notebooks/10.count-vowels.ipynb
      - Palindrome: Notebooks/11.palindrome.ipynb
      - Count words: Notebooks/12.count-words-in-a-string.ipynb
      - Downward Half Pyramid: Notebooks/13.half-pyramid.ipynb
      - Pyramid: Notebooks/14.pyramid.ipynb
      - Frequency of words: Notebooks/15.frequency-of-words.ipynb
      - Web Scraping: Notebooks/16.web-scraping.ipynb
      - Web Scraping - Books: Notebooks/17.books-scrape.ipynb
      - Web Scraping - Quotes: Notebooks/18.scrape-quotes.ipynb
      - Images: Notebooks/19.images.ipynb
      - Images - Exercise: Notebooks/20.image-exercise.ipynb
      - CSV Files: Notebooks/21.csv-files.ipynb
      - PDF Files: Notebooks/22.pdf-files.ipynb
      - PDF and CSV Exercise: Notebooks/23.pdf-and-csv-puzzle-exercise.ipynb
      - Emails: Notebooks/24.emails.ipynb
      - NumPy-1: Notebooks/25.numpy-1.ipynb
      - NumPy-2: Notebooks/26.numpy-2.ipynb
      - NumPy-3: Notebooks/27.numpy-3.ipynb
      - NumPy-Exercise: Notebooks/28.numpy-exercise.ipynb
    - Input Files:
      - blue_color.png: Inputs/blue_color.png
      - example.csv: Inputs/example.csv
      - example.jpg: Inputs/example.jpg
      - find_the_link.csv: Inputs/find_the_link.csv
      - Info.txt: Inputs/Info.txt
      - mask.png: Inputs/mask.png
      - new_computer: Inputs/new_computer.jpg
      - new_file.csv: Inputs/new_file.csv
      - pencils.jpg: Inputs/pencils.jpg
      - red_color.jpg: Inputs/red_color.jpg
      - red_save.jpg: Inputs/red_save.jpg
      - testpdf.pdf: Inputs/testpdf.pdf
      - Trump.jpg: Inputs/Trump.jpg
      - word_matrix.png: Inputs/word_matrix.png
      - Working_Business_Proposal.pdf: Inputs/Working_Business_Proposal.pdf
  - Assesments:
    - Statements: 6.statements-assesment.md
    - Functions: 8.functions-assesment.md
    - TicTacToe Project: 12.tic-tac-toe.md
    - Final: 25.final-assesment.md
  - Resources:
    - Tools Used: external-resources/index.md
