site_name: Python Class
site_author: Bhavya Sree Bindela
site_description: >-
  Python tutorial
theme:
  name: material
  custom_dir: material
  features:
    - tabs
plugins:
 - mknotebooks:
    execute: false
markdown_extensions:
  - pymdownx.arithmatex
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.betterem
  - pymdownx.superfences
  - markdown.extensions.footnotes
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.tables
  - markdown.extensions.abbr
  - markdown.extensions.md_in_html
extra_javascript:
  - javascripts/extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BhavyaSree
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/bhavyabindela
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/bhavyabindela
repo_name: BhavyaSree/PythonClass
repo_url: https://github.com/BhavyaSree/PythonClass
edit_uri: ""
# Page tree
nav:
  - Home: README.md
  - Getting started: 1.introduction.md
  - Strings & Lists: 2.strings-lists.md
  - Dictonaries, Sets & Tuples: 3.dictonaries-sets-tuples.md 
  - Operators: 4.operators.md
  - Conditional Statements: 5.conditional-statements.md
  - Methods and Functions: 7.methods-and-functions.md
  - Function Arguments: 9.function-arguments.md
  - Map Filter and Lambda Functions: 10.map-filter-lambda.md
  - Scope of Variables: 11.variables-scope.md
  - Assesments:
    - Statements: 6.statements-assesment.md
    - Functions: 8.functions-assesment.md
    - TicTacToe Project : 12.tic-tac-toe.md
  - Notebooks:
    - Day 1: Notebooks/Day1.ipynb 
    - Day 2: Notebooks/Day2.ipynb 
    - Day 3: Notebooks/Day3.ipynb
    - TicTacToe : Notebooks/TicTacToe.ipynb
  - Resources:
    - Tools Used: external-resources/index.md
